name: Publish Portal Content

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log level: 1=DEBUG, 2=INFO, 3=WARNING, 4=ERROR'
        required: false
        default: '2'
      skip_api_linting:
        description: 'Skip the API linting job'
        required: false
        default: 'false'
      skip_spell_check:
        description: 'Skip the spell check job'
        required: false
        default: 'false'
      publish:
        description: 'Publish to SwaggerHub Portal'
        required: false
        default: 'true'   
      product-folder:
        description: 'Path to the products folder.'
        required: false
        default: 'products'
      custom-words-file:
        description: 'Path to the custom words file for spell checking.'
        required: false
        default: './custom-words.txt'
  

env:
  SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
  LOG_LEVEL: ${{ github.event.inputs.log_level }}

jobs:
  publish-portal-content:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - name: Run SwaggerHub Portal Management Action
        uses: ./
        with:
          swaggerhub-api-key: ${{ secrets.SWAGGERHUB_API_KEY }}
          swaggerhub-portal-subdomain: ${{ vars.SWAGGERHUB_PORTAL_SUBDOMAIN }}
          swaggerhub-org-name: ${{ vars.SWAGGERHUB_ORG_NAME }}
          log-level: ${{ github.event.inputs.log_level || '2' }}
          skip-api-linting: ${{ github.event.inputs.skip_api_linting || 'false' }}
          skip-spell-check: ${{ github.event.inputs.skip_spell_check || 'false' }}
          publish: ${{ github.event.inputs.publish || 'true' }}
          product-folder: ${{ github.event.inputs.product-folder || 'products' }}
          # custom-words-file: ${{ github.event.inputs.custom-words-file || './custom-words.txt' }}